artifacts_root: artifacts

data_ingestion:
  root_data_dir: artifacts/data_ingestion
  source_url: https://github.com/Shivam-Shane/Learnerhub/raw/master/data.zip
  local_data_dir: artifacts/data_ingestion/data.zip
  unzip_data_dir: artifacts/data_ingestion
